spring:
  application:
    name: spring-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/halouprogramer/spring-config-repository.git
#          username: ***
#          password: ***
          basedir: ~/temp/gitlab
  rabbitmq:
    host: 192.168.114.129
    port: 5672
    username: admin
    password: admin


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 3636

management:
  endpoints:
    web:
      exposure:
        include: "*"